name: Build image and Push to DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    # Avoid the pipeline
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push (CPU)
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./Dockerfile.cpu
          tags: |
            juampahc/stickney-cpu:v1.0
            juampahc/stickney-cpu:latest
      
      - name: Build and push (CPUZ)
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./Dockerfile.cpuz
          tags: |
            juampahc/stickney-cpuz:v1.0
            juampahc/stickney-cpuz:latest

